### PR TITLE
Fix capitalization

### PR DESCRIPTION
**Pull request by LindsayHill**
Fixed sysoid tag capitalisation

### CODE REVIEW

**Comment by jfl88** [comment]
Thanks mate this appears to have resolved the issue with getting the adapter linking in the database.  The bloody capitalisation!!

**Comment by LindsayHill** [comment]
Ah, good to hear it works. Now you can focus on the rest of the adapter. I don't know if the device supports a running config backup, but I'd try to add that if possible. If it doesn't have a running config, I would do the startup config again (but save it as running config). That deals with a few assumptions that IMC makes about all devices having both running & startup config.

**Comment by jfl88** [comment]
Okay I'll give that a crack.  I had to take the reboot and save functions out of my Common CLI because it was erroring on running a backup.  Now at least I have the startup_config backup running the expect scripts.  It is still failing, but at least it is getting into the telnet, getting into enable and running the backup.  It's just failing on the TFTP transfer part now, hopefully I can get some time to keep looking at this tomorrow.

**Comment by LindsayHill** [comment]
Good stuff. It's a different set of problems once you're into debugging
Expect.

At least if it's using Telnet you can use Wireshark to help understand
what's going on. Also look for temporary files in the iMC temp directory -
those show the output received.

**Pull request merged**
